/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mtcnn_MTCNNDetector */

#ifndef _Included_com_mtcnn_MTCNNDetector
#define _Included_com_mtcnn_MTCNNDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mtcnn_MTCNNDetector
 * Method:    detectFaces
 * Signature: (Ljava/lang/String;Ljava/lang/String;FF)[Lcom/mtcnn/Face;
 */
JNIEXPORT jobjectArray JNICALL Java_com_mtcnn_MTCNNDetector_detectFaces
  (JNIEnv *, jobject, jstring, jstring, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
